language: node_js
os: linux

services:
  - docker

branches:
  only:
    - master
    - next
    - next-major
    - beta
    - alpha
    - /^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/

jobs:
  include:
    - stage: commit
      node_js: lts/*
      cache: npm
      script:
        - commitlint-travis
    - stage: test
      node_js: lts/*
      cache: npm
      script: npm run docker:test:ci
    - stage: release
      node_js: lts/*
      cache: npm
      script:
        - npm run docker:build:ci
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          all_branches: true
